import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  try {
    const { to, summary, title, speakers, transcriptPreview } = await req.json();

    if (!to || !summary) {
      return NextResponse.json({ error: "to and summary are required" }, { status: 400 });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "email-smtp.ap-northeast-1.amazonaws.com",
      port: parseInt(process.env.SMTP_PORT || "587", 10),
      secure: process.env.SMTP_SECURE === "true",
      auth: {
        user: process.env.SMTP_USER || "",
        pass: process.env.SMTP_PASS || "",
      },
    });

    const fromAddress = process.env.SMTP_FROM || "noreply@enartsu.co.jp";
    const dateStr = new Date().toLocaleDateString("ja-JP", { year: "numeric", month: "long", day: "numeric" });
    const meetingTitle = title || `文字起こし要約 ${dateStr}`;

    // Build speaker list HTML
    let speakerHtml = "";
    if (speakers && Object.keys(speakers).length > 0) {
      const entries = Object.entries(speakers)
        .filter(([_, name]) => name)
        .map(([id, name]) => `<li style="color: #666; font-size: 14px;">${(id as string).replace("SPEAKER_", "S")} = ${name}</li>`)
        .join("");
      if (entries) {
        speakerHtml = `
          <div style="margin-bottom: 24px; padding: 16px; background: #f8f9fa; border-radius: 8px; border-left: 4px solid #6366f1;">
            <h3 style="margin: 0 0 8px 0; font-size: 14px; color: #6366f1; text-transform: uppercase; letter-spacing: 1px;">話者一覧</h3>
            <ul style="margin: 0; padding-left: 20px;">${entries}</ul>
          </div>
        `;
      }
    }

    // Convert summary text to HTML with proper formatting
    const summaryHtml = summary
      .replace(/【(.+?)】/g, '<h2 style="color: #1e293b; font-size: 18px; margin: 24px 0 12px 0; padding-bottom: 6px; border-bottom: 2px solid #f59e0b;">$1</h2>')
      .replace(/^・(.+)$/gm, '<li style="margin-bottom: 6px; color: #374151; font-size: 14px; line-height: 1.7;">$1</li>')
      .replace(/(<li.*?<\/li>\n?)+/gs, '<ul style="margin: 0 0 16px 0; padding-left: 20px;">$&</ul>')
      .replace(/\n{2,}/g, "<br/><br/>")
      .replace(/\n/g, "<br/>");

    // Preview of transcript
    let previewHtml = "";
    if (transcriptPreview) {
      previewHtml = `
        <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #e5e7eb;">
          <h3 style="color: #9ca3af; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px;">文字起こしプレビュー（最初の20件）</h3>
          <div style="font-size: 13px; color: #6b7280; line-height: 1.8; white-space: pre-wrap;">${transcriptPreview}</div>
        </div>
      `;
    }

    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin: 0; padding: 0; background: #f3f4f6; font-family: 'Helvetica Neue', Arial, 'Hiragino Sans', sans-serif;">
  <div style="max-width: 640px; margin: 0 auto; padding: 24px;">
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%); border-radius: 16px 16px 0 0; padding: 32px 24px; text-align: center;">
      <div style="font-size: 12px; color: rgba(255,255,255,0.7); text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">AI Transcriber</div>
      <h1 style="margin: 0; color: white; font-size: 22px; font-weight: 700;">${meetingTitle}</h1>
      <div style="margin-top: 12px; color: rgba(255,255,255,0.8); font-size: 13px;">${dateStr}</div>
    </div>

    <!-- Content -->
    <div style="background: white; padding: 32px 24px; border-radius: 0 0 16px 16px; box-shadow: 0 4px 24px rgba(0,0,0,0.06);">
      ${speakerHtml}
      ${summaryHtml}
      ${previewHtml}
    </div>

    <!-- Footer -->
    <div style="text-align: center; padding: 24px 0; color: #9ca3af; font-size: 11px;">
      <p>Generated by AI Transcriber with GPU Acceleration</p>
    </div>
  </div>
</body>
</html>`;

    // Plain text fallback
    let plainText = `${meetingTitle}\n${dateStr}\n\n`;
    if (speakers && Object.keys(speakers).length > 0) {
      plainText += "=== 話者一覧 ===\n";
      Object.entries(speakers).forEach(([id, name]) => {
        if (name) plainText += `${(id as string).replace("SPEAKER_", "S")} = ${name}\n`;
      });
      plainText += "================\n\n";
    }
    plainText += summary;

    // Check SMTP credentials
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.log(`\n=== [Mail Mock] ===`);
      console.log(`To: ${to}`);
      console.log(`Subject: ${meetingTitle}`);
      console.log(`Body: ${plainText.slice(0, 200)}...`);
      return NextResponse.json({ success: true, mock: true });
    }

    const info = await transporter.sendMail({
      from: fromAddress,
      to,
      subject: `📝 ${meetingTitle}`,
      text: plainText,
      html,
    });

    console.log(`[Email] Summary sent to ${to}: ${info.messageId}`);
    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error: any) {
    console.error("[Email] Send failed:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
